version: '3.8'

services:
  # 프론트엔드 (Streamlit)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      - BACKEND_API_URL=http://backend:8000
    volumes:
      - ./frontend:/app
    restart: unless-stopped
    depends_on:
      - backend

  # 백엔드 (FastAPI)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - .:/app/parent  # 상위 디렉토리 마운트 (mcp_client_agent.py 접근용)
    environment:
      - PYTHONPATH=/app:/app/parent
    restart: unless-stopped
    depends_on:
      - mcp-server

  # MCP 서버 서비스
  mcp-server:
    build:
      context: ./mcp-server
      dockerfile: Dockerfile
    ports:
      - "8002:8000"  # 호스트 8002 포트로 매핑 (백엔드가 8000 사용)
    volumes:
      - ./mcp-server:/app
    restart: unless-stopped 